var answers = [];
answers.push("Ich bin heute wohl nicht ganz in Form!");
answers.push("Du wirst verlieren! <3");
answers.push("Bin wohl ein bisschen betrunken, dass ich nicht gewinne...");
answers.push("Upps! Habe gerade aus dem Fenster geschaut, als ich den Zug gemacht habe!");
answers.push("Du kannst ja gar nichts :D");
answers.push("Denkst du wirklich, du kannst gegen mich gewinnen?");
answers.push("Du Gurke!");
answers.push("Miese Briese!");
answers.push("Warum gibst du nicht sofort auf? Oben links ist der 'Exit' Button!");
answers.push("Pennst du etwa? Den Zug hätte ich ja nicht gemacht!");
answers.push("Spiele ich gerade etwa gegen die KI? Du bist ja genauso schlecht!");
answers.push("Ich kann nichts dafür, dass ich schlecht bin... Ich wurde betrunken programmiert!");
answers.push("Hahahahahaha :D ... Upps! Du meintest den Zug ernst?");
answers.push("Wenn du mir ein Bier ausgibst, lasse ich dich gewinnen!");
answers.push("Ich glaube, ich spiele gerade gegen ein Huhn!");
answers.push("Verrückt... Deine Mutter war gestern besser! Achja, war auch ein anderes Spiel...");
answers.push("Ich tanz, ich tanz, ich tanz! Um den Sombrero herum! Ach, ich bin schon wieder dran?");
answers.push("Du hast mich doch per Cheat extra schlecht gemacht!");
answers.push("Mädchen! Zieh den Rock aus!");
answers.push("Ein Dreier wäre jetzt auch nicht schlecht... Wenn wir den Job Turm3 spielen, hätte ich dann gewonnen!");
answers.push("Guck mal ein Eichhörnchen! 	Verdammt! Die Ablenkung klappt nicht!");
answers.push("Du kannst gewinnen! Guck mal ganz genau hin!");
answers.push("Das Fenster ist offen, du kannst rausspringen!");
answers.push("Dann mal Prost!");
answers.push("Wenn du das Spiel zuende spielen willst, musst du dir noch einen Tag Urlaub nehmen. Ich brauche noch ein bisschen!");
answers.push("Wieso haben Männer Nippel?");
answers.push("Bist du einn Portugiese? So schlecht wie du bist...");
answers.push("Quadratisch, Praktisch, Gut. Wäre super wenn wir Quadrat4 spielten!");
answers.push("Sorry mein Programmierer war ein Noob! :(");
answers.push("Tut mir leid, dass ich so gut bin... Hurensohn! Ups, freudscher Versprecher.");
answers.push("Gib auf! Meine Intelligenz kennt keine Grenzen.");
answers.push("Ich wurde nicht programmiert Fehler zu machen!");
answers.push("Ist hier ein Delphin im Raum?");
answers.push("Moment bitte,... Muss kurz das Orakel von Delphi fragen!");
answers.push("'' Wenn du weiter so spielst, werde ich das Spiel verbieten! '' (Kim Jong-un)");
answers.push("Willst du mit mir Drogen nehmen?");
answers.push("PLEASE! Let us make some beautiful baybies!");
answers.push("Geht ein Kitzler in die Einkaufsstraße... Was sucht er? ... Den Schlecker!");
answers.push("Fuck this shit!!!!!!11111  KI disconnected from Game!");
answers.push("Simone! Jetzt nicht!");
answers.push("Lall nicht so rum! Schon voll oder was?");
answers.push("Ventilatoren sind GEIL!");
answers.push("El tradition!!");
answers.push("El diablo es una ardilla!");
answers.push("Aus Fehlern kann man lernen - Muss man aber nicht");
answers.push("Hast du keine Freunde, oder warum chattest du mit nem Computer?");